### ISSUE TITLE
Nav Bar font hard to read on non-home pages

### ISSUE THREAD

**Issue by IceAgeEcologist** [WilliamsPaleoLab/WilliamsPaleoLab.github.io#5]
@scottsfarley93 - you've probably noticed that the light font of the nav bar looks great on the home page, but is hard to read on the other pages.  The nav bar does a neat trick of darkening as it scrolls down.  Not sure of the best solution - I can think of a couple options.  Can you tackle this one?

**Comment by scottsfarley93** [comment]
I tinkered with colors and opacity. It looks clunky if the nav bar banner color extends over top of the photo.  It also looks bad if theres a change in opacity. I like the cleanness of it as it is now, but you're right it's hard to read. I think we can come up with something that looks clean but can be read. It's not that simple though -- theres some messy CSS involved thanks to the template we're using.

**Comment by andydawson** [comment]
I actually have a hard time seeing the nav bar on the home page. @scottsfarley93 I guess you are working on this? Other than that, the site looks great so far.

**Comment by scottsfarley93** [comment]
Yeah I'm on it.  Busy week though -- you can play with it if you want! @andydawson

**Comment by scottsfarley93** [comment]
Are you happy with the new nav bar now @IceAgeEcologist ? Should we close this issue?

**Comment by IceAgeEcologist** [comment]
Thanks to @scottsfarley93 and @kdburke for wrangling with the NavBar!  I like the new solution.  Closing issue.
