### ISSUE TITLE
Embedding links in news markdown files

### ISSUE THREAD

**Issue by IceAgeEcologist** [WilliamsPaleoLab/WilliamsPaleoLab.github.io#6]
@scottsfarley93 - a minor one - I'd like to embed links in our news items.  I've created a couple of sample news items, and have used markdown syntax for the links, but they don't seem to be rendering properly.  Thoughts?

**Comment by scottsfarley93** [comment]
Fixed this.  Now, instead of putting things in the yaml `blurb` write full markdown below the yaml header.  See the template for an example.
