### ISSUE TITLE
Alumni photos

### ISSUE THREAD

**Issue by IceAgeEcologist** [WilliamsPaleoLab/WilliamsPaleoLab.github.io#8]
I stripped down the alumni profiles in people_layout to remove the bios, but this then led to a weird formatting.  I temporarily solved by removing photos, but it'd be nice to add these back.  Scott, I'm hoping you can do some mild html fixes here - let's discuss.

**Comment by scottsfarley93** [comment]
I'll take a look at it. Let me see what's up.

**Comment by scottsfarley93** [comment]
Fixed.  I'm not sure why but the names were being displayed inline instead of as block (taking up just the space they need rather than the whole line).  i'm unsure of why it only happened for the alumni, but I fixed it by wrapping each person in the alumni section in its own div. 

Closing.
